trigger: none

pool: Deepakagent

steps:

- task: TerraformInstaller@1
  displayName: 'terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Deepakservice Connection'
    backendAzureRmStorageAccountName: 'deep56stg'
    backendAzureRmContainerName: 'deepcnt'
    backendAzureRmKey: 'Dev.terraform.tfstate'

- task: TerraformTask@5
  displayName: 'terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'terraform fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'Deepakservice Connection'

- task: TerraformTask@5
  displayName: 'terraform plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Deepakservice Connection'

- task: TerraformTask@5
  displayName: 'terraform apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Deepakservice Connection'


